"""
################################ COMMON LIBRARY ################################
#
# Please DO NOT edit this file unless you wish to contribute common code.
# Please see the documentation in the README of the repository for more details.
# https://github.palantir.build/foundry/bellhop-authoring
#
################################################################################
"""

import codecs
import base64
import pyspark.sql.functions as F
from bellhop_authoring_api.bellhop_authoring_api_config_source import (
    SourceConfig,
    Table,
)
from pyspark.sql import types as T, Column
from enum import Enum


# Constant types
STRING_LIKE_TYPES = T.StringType
INTEGER_LIKE_TYPES = (T.IntegerType, T.ByteType, T.ShortType, T.LongType)
DOUBLE_LIKE_TYPES = (T.DoubleType, T.FloatType, T.DecimalType)
BOOLEAN_LIKE_TYPES = T.BooleanType
DATE_LIKE_TYPES = T.DateType
TIMESTAMP_LIKE_TYPES = T.TimestampType
NULL_LIKE_STRINGS = ["#n/a", "n/a", "null", "(null)", "none", "nil", "undefined", ""]
TRUTHY_STRINGS = ["true", "t", "yes", "y", "active", "a", "1"]
FALSEY_STRINGS = ["false", "f", "no", "n", "inactive", "i", "0"]
DATE_PARSE_TIMEZONE = "America/New_York"


# Enumerate FieldNameAlias
class FieldNameAlias(str, Enum):
    raw_field_name = "raw_field_name"
    field_type = "field_type"
    object_name = "object_name"
    domain_name = "domain_name"


# PUBLIC FUNCTIONS


# Removes duplicate rows using .distinct()
def keep_distinct_rows(
    primary_dataframe,
    _cleaning_metadata_dataframe,
    _table: Table,
    _source_config: SourceConfig,
):
    return primary_dataframe.distinct()


# Converts every column in the dataframe to a clean version
def convert_all_columns_to_clean_types(
    primary_dataframe,
    cleaning_metadata_dataframe,
    table: Table,
    _source_config: SourceConfig,
):
    column_types = _get_column_cleaning_metadata_for_table(
        table.table_name, cleaning_metadata_dataframe
    )
    return _convert_to_clean(primary_dataframe, column_types)


# Parse the decimal timestamp column extracted from SLT into a timestamp type.
def parse_timestamp_column(
    primary_dataframe,
    cleaning_metadata_dataframe,
    table: Table,
    _source_config: SourceConfig,
):
    timestamp_column = "/PALANTIR/TIMESTAMP"
    parsed_timestamp_column = timestamp_column + "_PARSED"

    if timestamp_column in primary_dataframe.columns:
        primary_dataframe = primary_dataframe.withColumn(
            parsed_timestamp_column,
            F.to_timestamp(F.col(timestamp_column).cast("string"), "yyyyMMddHHmmss"),
        )

    return primary_dataframe


# Decodes RAW column types in string
def decode_raw_type_columns(
    primary_dataframe,
    cleaning_metadata_dataframe,
    table: Table,
    _source_config: SourceConfig,
):
    column_types = _get_column_cleaning_metadata_for_table(
        table.table_name, cleaning_metadata_dataframe
    )
    cols_to_update = dict()
    for col_name, coltype, domain in column_types:
        if col_name in primary_dataframe.columns:
            if "RAW" in coltype:
                cols_to_update[col_name] = _convert_raw(F.col(col_name), col_name)

    return primary_dataframe.select(
        *[
            cols_to_update.get(col_name, col_name)
            for col_name in primary_dataframe.columns
        ]
    )


# Converts every column in the dataframe to a clean version for INFOR
def convert_all_columns_to_clean_types_infor(
    primary_dataframe,
    cleaning_metadata_dataframe,
    table: Table,
    _source_config: SourceConfig,
):
    column_types = _get_column_cleaning_metadata_for_table(
        table.table_name, cleaning_metadata_dataframe
    )
    return _convert_to_clean_infor(primary_dataframe, column_types)


# PRIVATE FUNCTIONS
# These functions are used as utils
def _convert_to_clean(df, column_types):
    """
    converts appropriate dataset based on field_metadata
    """
    cols_to_update = dict()
    for col_name, coltype, domain in column_types:
        if col_name in df.columns:
            if coltype == "TIMS":
                cols_to_update[col_name] = _convert_tims(F.col(col_name), col_name)
            elif coltype == "DATS":
                cols_to_update[col_name] = _convert_dats(F.col(col_name), col_name)
            elif coltype == "DEC":
                cols_to_update[col_name] = _convert_dec(
                    F.col(col_name), col_name, domain
                )
            elif "INT" in coltype:
                cols_to_update[col_name] = _convert_int(F.col(col_name), col_name)
            elif "RAW" in coltype:
                cols_to_update[col_name] = _convert_raw(F.col(col_name), col_name)
    # to get the latest data types for next step
    df = df.select(*[cols_to_update.get(col_name, col_name) for col_name in df.columns])

    cols_to_update = dict()
    for col in df.schema:
        col_name = col.name
        col_type = col.dataType
        if isinstance(col.dataType, STRING_LIKE_TYPES):
            cols_to_update[col_name] = _parse_cols_as_string(F.col(col_name), col_name)
        elif isinstance(col.dataType, BOOLEAN_LIKE_TYPES):
            cols_to_update[col_name] = _parse_cols_as_bool(
                F.col(col_name), col_type, col_name
            )
        elif isinstance(col.dataType, DOUBLE_LIKE_TYPES):
            cols_to_update[col_name] = _parse_cols_as_double(F.col(col_name), col_name)

    return df.select(
        *[cols_to_update.get(col_name, col_name) for col_name in df.columns]
    )


def _get_column_cleaning_metadata_for_table(table_name, cleaning_metadata):
    """
    Gets the ABAP type for each column
    """
    return (
        cleaning_metadata.filter(F.col(FieldNameAlias.object_name) == table_name)
        .select(
            FieldNameAlias.raw_field_name,
            FieldNameAlias.field_type,
            FieldNameAlias.domain_name,
        )
        .collect()
    )


def _parse_and_replace_aliases_in_col(column, col_name, alias_list, val, default_val):
    """
    Conditionally replace common aliases in a String column according to `alias_list`.
    """
    return (
        F.when(F.lower(column).isin(alias_list), val)
        .otherwise(default_val)
        .alias(col_name)
    )


def _parse_nulls_from_string_col(column, col_name):
    """
    Interpret and explicitly cast nulls in a String column according to `NULL_LIKE_STRINGS` constant.
    """
    return _parse_and_replace_aliases_in_col(
        column, col_name, NULL_LIKE_STRINGS, F.lit(None), column
    )


def _parse_cols_as_string(column, col_name):
    """
    Interpret, parse, and clean a column as a Spark String.
    Whitespace will be trimmed from either side of the source data for each row.
    """
    result_column = F.trim(column.cast("string"))

    result_column = _parse_nulls_from_string_col(result_column, col_name)
    return result_column.alias(col_name)


def _parse_cols_as_bool(column, column_data_type, col_name):
    """
    Interpret and parse a column as a Spark Boolean.
    If the source column schema is a String, parse booleans
    according to `TRUTHY_STRINGS` and `FALSEY_STRINGS` constants.
    """
    if isinstance(column_data_type, T.StringType):
        result_column = _parse_and_replace_aliases_in_col(
            column, col_name, TRUTHY_STRINGS, "true", column
        )
        result_column = _parse_and_replace_aliases_in_col(
            result_column, col_name, FALSEY_STRINGS, "false", result_column
        )
    else:
        result_column = column
    return result_column.cast("boolean").alias(col_name)


def _parse_cols_as_double(column, col_name):
    """
    Interpret and parse a column as a Spark Double.
    """
    return column.cast("double").alias(col_name)


def _convert_tims(column, col_name):
    """
    converts timestamp string to long
    """
    return (
        F.when(column == "000000", F.lit(None))
        .otherwise((F.regexp_replace(column, ":", "").cast("long")))
        .alias(col_name)
    )


def _convert_dats(column, col_name, date_format="yyyyMMdd"):
    """
    converts date string to date
    """
    return (
        F.when(column == "00000000", F.lit(None))
        .otherwise(F.to_date(column, date_format))
        .alias(col_name)
    )


def _convert_dec(column, col_name, domain="TSTMP"):
    if domain == "TZNTSTMPS":
        parsing = F.to_timestamp(column.cast("string"), "yyyyMMddHHmmss")
    elif domain == "COM_TSTMP":
        parsing = F.to_utc_timestamp(
            F.to_timestamp(column.cast("string"), "yyyyMMddHHmmss"), DATE_PARSE_TIMEZONE
        )
    elif domain == "TZNTSTMPL":
        parsing = F.to_timestamp(column.cast("string"), "yyyyMMddHHmmss")
    else:
        parsing = column.cast("double")
    return parsing.alias(col_name)


def _convert_int(column, col_name):
    return column.cast("int").alias(col_name)


def _convert_raw(column: Column, col_name: str) -> Column:
    @F.udf(T.StringType())
    def encode_binary(input_binary):
        # If `input_binary` is `None`, then the `base64.b64decode` would throw
        # an error if we do not return early
        if input_binary is None:
            return None

        decode_hex = codecs.getencoder("hex_codec")
        # only need one base64 decode because spark cast to string does one base64 encode
        converted = base64.b64decode(input_binary)
        return decode_hex(converted)[0].decode("ascii").upper()

    return encode_binary(column.cast("string")).alias(col_name)


# INFOR SPECIFIC FUNCTIONS
def _convert_to_clean_infor(df, column_types):
    """
    converts appropriate dataset based on field_metadata
    """
    cols_to_update = dict()
    for col_name, coltype, domain in column_types:
        if col_name in df.columns:
            if coltype == "date-time":
                cols_to_update[col_name] = _convert_timestamp_infor(
                    F.col(col_name), col_name
                )
    # to get the latest data types for next step
    df = df.select(*[cols_to_update.get(col_name, col_name) for col_name in df.columns])
    return df


def _convert_timestamp_infor(column, col_name):
    """
    converts timestamp string to TimestampType
    """
    return F.to_timestamp(column, "yyyy-MM-dd'T'HH:mm:ss.SSSSSS").alias(col_name)
